version: "3.3"

services:
  proxy:
    image: traefik
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic:/etc/traefik/dynamic
      - ./letsencrypt:/etc/letsencrypt
      - ./certs:/etc/certs

networks:
  proxy:
    driver: bridge
