[global]
  sendAnonymousUsage = false

[log]
  level = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

  [entryPoints.postgres]
    address = ":5432"

  [entryPoints.mysql]
    address = ":3306"

[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"
    watch = true

  [providers.docker]
    exposedbydefault = false

[api]
  insecure = true
  dashboard = true
